// Generated by CoffeeScript 1.6.2
(function() {
  var Queue;

  Queue = (function() {
    function Queue() {
      this.stack = [];
    }

    Queue.prototype.push = function(data) {
      this.stack.push(data);
      return this.run();
    };

    Queue.prototype.run = function() {
      var elt, _i, _len, _ref, _results;

      if (this.running) {
        _ref = this.stack.slice(0);
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          elt = _ref[_i];
          this.worker(elt);
          _results.push(this.stack.splice(this.stack.indexOf(elt), 1));
        }
        return _results;
      }
    };

    Queue.prototype.start = function() {
      this.running = true;
      return this.run();
    };

    Queue.prototype.stop = function() {
      return this.running = false;
    };

    Queue.prototype.worker = function() {
      throw "Worker not implemented";
    };

    return Queue;

  })();

}).call(this);
