// Generated by CoffeeScript 1.6.2
(function() {
  var Queuey;

  Queuey = (function() {
    function Queuey() {
      this.stack = [];
    }

    Queuey.prototype.push = function(data) {
      this.stack.push(data);
      return this.run();
    };

    Queuey.prototype.run = function() {
      while (this.stack.length > 0 && this.running) {
        this.worker(this.stack.shift());
      }
    };

    Queuey.prototype.start = function() {
      this.running = true;
      return this.run();
    };

    Queuey.prototype.stop = function() {
      return this.running = false;
    };

    Queuey.prototype.worker = function() {
      throw "Worker not implemented";
    };

    return Queuey;

  })();

}).call(this);
